#include <stdio.h>
#include <string.h>
#include <stdlib.h>

// Cria a resposta HTML em um buffer maior
char html[32768]; // 32KB - tamanho para HTML completo

extern char html[32768];

void preencher_html() {
    snprintf(html, sizeof(html),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html\r\n"
        "\r\n"
        "<!DOCTYPE html>\n"
        "<html lang=\"pt-BR\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Painel de Controle - Armazém XYZ</title>\n"
        "    <style>\n"
        "        :root{--cor-primaria:#005A9C;--cor-fundo:#f4f7f9;--cor-painel:#ffffff;--cor-texto:#333333;--cor-sucesso:#28a745;--cor-aviso:#ffc107;--cor-borda:#dee2e6;--sombra-suave:0 4px 8px rgba(0,0,0,0.05)}\n"
        "        *{margin:0;padding:0;box-sizing:border-box}\n"
        "        .main-header, .main-footer {background-color: var(--cor-primaria);color: white;padding: 1rem 2rem;text-align: center;}\n"
        "        .dashboard-container {display: flex;flex-wrap: wrap; padding: 1.5rem;gap: 1.5rem;}\n"
        "        .warehouse-view-column {flex: 2; min-width: 350px;}\n"
        "        .controls-column {flex: 1; min-width: 300px;}\n"
        "        section {background-color: var(--cor-painel);padding: 1.5rem;border-radius: 8px;box-shadow: var(--sombra-suave);margin-bottom: 1.5rem;}\n"
        "        h2, h3 {margin-bottom: 1rem;color: var(--cor-primaria);}\n"
        "        h3 {font-size: 1.1rem;border-bottom: 1px solid var(--cor-borda);padding-bottom: 0.5rem;}\n"
        "        body {font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif;background-color: var(--cor-fundo);color: var(--cor-texto);line-height: 1.6;}\n"
        "        .warehouse-layout {display: flex;align-items: center;justify-content: center;gap: 1rem;}\n"
        "        .rack-container {display: grid;grid-template-columns: repeat(5, 1fr);gap: 0.5rem;flex-grow: 1;}\n"
        "        .rack-cell {background-color: #e9ecef;border: 1px solid #ccc;border-radius: 4px;aspect-ratio: 1 / 1; display: flex;align-items: center;justify-content: center;font-weight: bold;font-size: 0.9rem;transition: background-color 0.3s ease;cursor: pointer;}\n"
        "        .rack-cell.occupied {background-color: var(--cor-aviso);color: var(--cor-texto);border-color: #e6a800;}\n"
        "        .rack-cell.occupied:hover {background-color: #e6a800;transform: scale(1.05);}\n"
        "        .rack-cell:not(.occupied) {cursor: not-allowed;opacity: 0.6;}\n"
        "        .legend {display: flex;justify-content: center;gap: 2rem;margin-top: 1rem;padding: 1rem;background-color: #f8f9fa;border-radius: 4px;}\n"
        "        .legend-item {display: flex;align-items: center;gap: 0.5rem;}\n"
        "        .legend-color {width: 20px;height: 20px;border-radius: 4px;border: 1px solid #ccc;}\n"
        "        .legend-color.occupied {background-color: var(--cor-aviso);}\n"
        "        .legend-color.empty {background-color: #e9ecef;}\n"
        "        .conveyor {border: 2px dashed var(--cor-primaria);padding: 1rem 0.5rem;min-height: 200px;display: flex;flex-direction: column;align-items: center;text-align: center;}\n"
        "        .pallet-info {margin-top: 1rem;font-weight: bold;color: var(--cor-sucesso);}\n"
        "        .control-group {margin-bottom: 2rem;}\n"
        "        form {display: flex;flex-direction: column;gap: 0.75rem;}\n"
        "        input[type=\"text\"], input[type=\"number\"], input[type=\"date\"] {width: 100%;padding: 0.75rem;border: 1px solid var(--cor-borda);border-radius: 4px;font-size: 1rem;}\n"
        "        button {padding: 0.75rem 1rem;border: none;border-radius: 4px;background-color: var(--cor-primaria);color: white;font-size: 1rem;font-weight: bold;cursor: pointer;transition: background-color 0.2s ease;}\n"
        "        button:hover {background-color: #004a80;}\n"
        "        #electromagnet-control {margin-top: 1rem;display: flex;align-items: center;gap: 1rem;}\n"
        "        #log-container {background-color: #f8f9fa;border: 1px solid var(--cor-borda);border-radius: 4px;padding: 1rem;height: 150px;overflow-y: auto;font-family: \"Courier New\", monospace;font-size: 0.9rem;}\n"
        "        #log-container p {padding-bottom: 0.5rem;border-bottom: 1px solid #eee;}\n"
        "        #log-container p:last-child {border-bottom: none;}\n"
        "        .popup-overlay {position: fixed;top: 0;left: 0;width: 100%;height: 100%;background-color: rgba(0, 0, 0, 0.5);display: none;justify-content: center;align-items: center;z-index: 1000;}\n"
        "        .popup {background-color: white;padding: 2rem;border-radius: 8px;box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);text-align: center;max-width: 400px;width: 90%;}\n"
        "        .popup h3 {margin-bottom: 1rem;color: var(--cor-primaria);}\n"
        "        .popup-buttons {display: flex;gap: 1rem;justify-content: center;margin-top: 1.5rem;}\n"
        "        .popup-buttons button {padding: 0.5rem 1.5rem;}\n"
        "        .popup-buttons button.cancel {background-color: #6c757d;}\n"
        "        .popup-buttons button.cancel:hover {background-color: #5a6268;}\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "    <header class=\"main-header\"><h1>Painel de Controle - Armazém Automatizado XYZ</h1></header>\n"
        "    <main class=\"dashboard-container\">\n"
        "        <div class=\"warehouse-view-column\">\n"
        "            <section id=\"visualizacao-rack\">\n"
        "                <h2>Layout do Armazém</h2>\n"
        "                <div class=\"warehouse-layout\">\n"
        "                    <div id=\"entry-conveyor\" class=\"conveyor\">\n"
        "                        <h3>Entrada</h3>\n"
        "                        <div class=\"pallet-info\" id=\"pallet-on-entry\"><p></p></div>\n"
        "                    </div>\n"
        "                    <div class=\"rack-container\">\n"
        "                        <div class=\"rack-cell\" data-position=\"A1\">A1</div><div class=\"rack-cell\" data-position=\"A2\">A2</div><div class=\"rack-cell\" data-position=\"A3\">A3</div><div class=\"rack-cell\" data-position=\"A4\">A4</div><div class=\"rack-cell\" data-position=\"A5\">A5</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"B1\">B1</div><div class=\"rack-cell\" data-position=\"B2\">B2</div><div class=\"rack-cell\" data-position=\"B3\">B3</div><div class=\"rack-cell\" data-position=\"B4\">B4</div><div class=\"rack-cell\" data-position=\"B5\">B5</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"C1\">C1</div><div class=\"rack-cell\" data-position=\"C2\">C2</div><div class=\"rack-cell\" data-position=\"C3\">C3</div><div class=\"rack-cell\" data-position=\"C4\">C4</div><div class=\"rack-cell\" data-position=\"C5\">C5</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"D1\">D1</div><div class=\"rack-cell\" data-position=\"D2\">D2</div><div class=\"rack-cell\" data-position=\"D3\">D3</div><div class=\"rack-cell\" data-position=\"D4\">D4</div><div class=\"rack-cell\" data-position=\"D5\">D5</div>\n"
        "                    </div>\n"
        "                    <div id=\"exit-conveyor\" class=\"conveyor\">\n"
        "                        <h3>Saída</h3><div class=\"pallet-info\" id=\"pallet-on-exit\"></div>\n"
        "                    </div>\n"
        "                </div>\n"
        "                <div class=\"legend\">\n"
        "                    <div class=\"legend-item\"><div class=\"legend-color occupied\"></div><span>Ocupado (com pallet armazenado)</span></div>\n"
        "                    <div class=\"legend-item\"><div class=\"legend-color empty\"></div><span>Vazio (sem pallet)</span></div>\n"
        "                </div>\n"
        "            </section>\n"
        "        </div>\n"
        "        <div class=\"controls-column\">\n"
        "            <section id=\"painel-controle\">\n"
        "                <h2>Painel de Controle</h2>\n"
        "                <div class=\"control-group\" id=\"pallet-operations\">\n"
        "                    <h3>Operações com Pallets</h3>\n"
        "                    <form id=\"store-form\"><p>Armazenar pallet da esteira de entrada.</p><button type=\"submit\">Iniciar Armazenamento</button></form>\n"
        "                    <form id=\"retrieve-form\"><label for=\"pallet-position-input\">Retirar pallet da posição:</label><input type=\"text\" id=\"pallet-position-input\" name=\"position\" placeholder=\"Ex: B3\" required><button type=\"submit\">Iniciar Retirada</button></form>\n"
        "                </div>\n"
        "                <div class=\"control-group\" id=\"manual-control\">\n"
        "                    <h3>Controle Manual</h3>\n"
        "                    <form id=\"move-form\">\n"
        "                        <label for=\"coord-x\">Eixo X:</label><input type=\"number\" id=\"coord-x\" name=\"x\" min=\"0\" value=\"0\">\n"
        "                        <label for=\"coord-y\">Eixo Y:</label><input type=\"number\" id=\"coord-y\" name=\"y\" min=\"0\" value=\"0\">\n"
        "                        <label for=\"coord-z\">Eixo Z:</label><input type=\"number\" id=\"coord-z\" name=\"z\" min=\"0\" value=\"0\">\n"
        "                        <button type=\"submit\">Mover para Coordenada</button>\n"
        "                    </form>\n"
        "                    <div id=\"electromagnet-control\"><button id=\"electromagnet-toggle-btn\">Ativar Eletroímã</button><span>Status: <b id=\"electromagnet-status\">Desativado</b></span></div>\n"
        "                </div>\n"
        "            </section>\n"
        "            <section id=\"historico\">\n"
        "                <h2>Histórico de Movimentações</h2>\n"
        "                <form id=\"history-filter-form\"><label for=\"filter-date\">Filtrar por data:</label><input type=\"date\" id=\"filter-date\" name=\"date\"><button type=\"submit\">Filtrar</button></form>\n"
        "                <div id=\"log-container\"></div>\n"
        "            </section>\n"
        "        </div>\n"
        "    </main>\n"
        "    <div class=\"popup-overlay\" id=\"popup-overlay\">\n"
        "        <div class=\"popup\">\n"
        "            <h3>Confirmar Remoção</h3>\n"
        "            <p>Deseja remover o pallet da posição <span id=\"popup-position\"></span>?</p>\n"
        "            <div class=\"popup-buttons\"><button id=\"confirm-remove\">Sim</button><button class=\"cancel\" id=\"cancel-remove\">Não</button></div>\n"
        "        </div>\n"
        "    </div>\n"
        "    <footer class=\"main-footer\"><p>Interface de Controle v1.0 - Status do Sistema: <span id=\"system-status\">Online</span></p></footer>\n"
        "    <script>\n"
        "        let historyLog = [];\n"
        "        let electromagnetActive = false;\n"
        "        document.addEventListener('DOMContentLoaded', function() {\n"
        "            const rackCells = document.querySelectorAll('.rack-cell');\n"
        "            const popupOverlay = document.getElementById('popup-overlay');\n"
        "            const popupPosition = document.getElementById('popup-position');\n"
        "            const confirmButton = document.getElementById('confirm-remove');\n"
        "            const cancelButton = document.getElementById('cancel-remove');\n"
        "            const electromagnetBtn = document.getElementById('electromagnet-toggle-btn');\n"
        "            const electromagnetStatus = document.getElementById('electromagnet-status');\n"
        "            let currentSlot = null;\n"
        "            const storeForm = document.getElementById('store-form');\n"
        "            const retrieveForm = document.getElementById('retrieve-form');\n"
        "            const moveForm = document.getElementById('move-form');\n"
        "            const filterForm = document.getElementById('history-filter-form');\n"
        "            initializeHistory();\n"
        "            rackCells.forEach(cell => {\n"
        "                cell.addEventListener('click', function() {\n"
        "                    if (this.classList.contains('occupied')) {\n"
        "                        currentSlot = this.getAttribute('data-position');\n"
        "                        popupPosition.textContent = currentSlot;\n"
        "                        popupOverlay.style.display = 'flex';\n"
        "                    }\n"
        "                });\n"
        "            });\n"
        "            confirmButton.addEventListener('click', function() {\n"
        "                if (currentSlot) {\n"
        "                    addToHistory(`Pallet retirado da posição ${currentSlot}.`);\n"
        "                    popupOverlay.style.display = 'none';\n"
        "                    currentSlot = null;\n"
        "                }\n"
        "            });\n"
        "            cancelButton.addEventListener('click', function() { popupOverlay.style.display = 'none'; currentSlot = null; });\n"
        "            popupOverlay.addEventListener('click', function(e) { if (e.target === popupOverlay) { popupOverlay.style.display = 'none'; currentSlot = null; } });\n"
        "            storeForm.addEventListener('submit', function(e) { e.preventDefault(); addToHistory(\"Pallet armazenado da esteira de entrada.\"); });\n"
        "            retrieveForm.addEventListener('submit', function(e) {\n"
        "                e.preventDefault();\n"
        "                const positionInput = document.getElementById('pallet-position-input');\n"
        "                const position = positionInput.value.trim().toUpperCase();\n"
        "                if (position) { addToHistory(`Pallet retirado da posição ${position}.`); positionInput.value = ''; }\n"
        "            });\n"
        "            moveForm.addEventListener('submit', function(e) {\n"
        "                e.preventDefault();\n"
        "                const x = document.getElementById('coord-x').value;\n"
        "                const y = document.getElementById('coord-y').value;\n"
        "                const z = document.getElementById('coord-z').value;\n"
        "                addToHistory(`Mecanismo movido para X:${x} Y:${y} Z:${z}.`);\n"
        "            });\n"
        "            electromagnetBtn.addEventListener('click', function() {\n"
        "                electromagnetActive = !electromagnetActive;\n"
        "                electromagnetStatus.textContent = electromagnetActive ? 'Ativado' : 'Desativado';\n"
        "                electromagnetBtn.textContent = electromagnetActive ? 'Desativar Eletroímã' : 'Ativar Eletroímã';\n"
        "                addToHistory(`Eletroímã ${electromagnetActive ? 'ativado' : 'desativado'}.`);\n"
        "            });\n"
        "            filterForm.addEventListener('submit', function(e) {\n"
        "                e.preventDefault();\n"
        "                const filterDate = document.getElementById('filter-date').value;\n"
        "                if (filterDate) { addToHistory(`Filtro aplicado para a data: ${filterDate}.`); }\n"
        "            });\n"
        "            function initializeHistory() { historyLog = []; }\n"
        "            function addToHistory(message, customTime = null) {\n"
        "                const now = new Date();\n"
        "                const time = customTime || `${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}:${now.getSeconds().toString().padStart(2, '0')}`;\n"
        "                const logEntry = `${time} - ${message}`;\n"
        "                historyLog.unshift(logEntry);\n"
        "                updateHistoryDisplay();\n"
        "            }\n"
        "            function updateHistoryDisplay() {\n"
        "                const logContainer = document.getElementById('log-container');\n"
        "                logContainer.innerHTML = '';\n"
        "                historyLog.forEach(entry => {\n"
        "                    const p = document.createElement('p');\n"
        "                    p.textContent = entry;\n"
        "                    logContainer.appendChild(p);\n"
        "                });\n"
        "            }\n"
        "        });\n"
        "    </script>\n"
        "</body>\n"
        "</html>\n");
}

