#include <stdio.h>
#include <string.h>
#include <stdlib.h>

char html[8192];  // aumentei o buffer, já que a página é bem maior

void preencher_html() {
    snprintf(html, sizeof(html),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html\r\n"
        "\r\n"
        "<!DOCTYPE html>\n"
        "<html lang=\"pt-BR\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Painel de Controle - Armazém XYZ</title>\n"
        "    <style>\n"
        "        :root { --cor-primaria: #005A9C; --cor-fundo: #f4f7f9; --cor-painel: #ffffff; --cor-texto: #333333; --cor-sucesso: #28a745; --cor-aviso: #ffc107; --cor-borda: #dee2e6; --sombra-suave: 0 4px 8px rgba(0,0,0,0.05); }\n"
        "        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
        "        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: var(--cor-fundo); color: var(--cor-texto); line-height: 1.6; }\n"
        "        .main-header, .main-footer { background-color: var(--cor-primaria); color: white; padding: 1rem 2rem; text-align: center; }\n"
        "        .dashboard-container { display: flex; flex-wrap: wrap; padding: 1.5rem; gap: 1.5rem; }\n"
        "        .warehouse-view-column { flex: 2; min-width: 350px; }\n"
        "        .controls-column { flex: 1; min-width: 300px; }\n"
        "        section { background-color: var(--cor-painel); padding: 1.5rem; border-radius: 8px; box-shadow: var(--sombra-suave); margin-bottom: 1.5rem; }\n"
        "        h2, h3 { margin-bottom: 1rem; color: var(--cor-primaria); }\n"
        "        h3 { font-size: 1.1rem; border-bottom: 1px solid var(--cor-borda); padding-bottom: 0.5rem; }\n"
        "        .warehouse-layout { display: flex; align-items: center; justify-content: center; gap: 1rem; }\n"
        "        .rack-container { display: grid; grid-template-columns: repeat(5, 1fr); gap: 0.5rem; flex-grow: 1; }\n"
        "        .rack-cell { background-color: #e9ecef; border: 1px solid #ccc; border-radius: 4px; aspect-ratio: 1 / 1; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 0.9rem; transition: background-color 0.3s ease; }\n"
        "        .rack-cell.occupied { background-color: var(--cor-aviso); color: var(--cor-texto); border-color: #e6a800; }\n"
        "        .conveyor { border: 2px dashed var(--cor-primaria); padding: 1rem 0.5rem; min-height: 200px; display: flex; flex-direction: column; align-items: center; text-align: center; }\n"
        "        .pallet-info { margin-top: 1rem; font-weight: bold; color: var(--cor-sucesso); }\n"
        "        .control-group { margin-bottom: 2rem; }\n"
        "        form { display: flex; flex-direction: column; gap: 0.75rem; }\n"
        "        input[type='text'], input[type='number'], input[type='date'] { width: 100%%; padding: 0.75rem; border: 1px solid var(--cor-borda); border-radius: 4px; font-size: 1rem; }\n"
        "        button { padding: 0.75rem 1rem; border: none; border-radius: 4px; background-color: var(--cor-primaria); color: white; font-size: 1rem; font-weight: bold; cursor: pointer; transition: background-color 0.2s ease; }\n"
        "        button:hover { background-color: #004a80; }\n"
        "        #electromagnet-control { margin-top: 1rem; display: flex; align-items: center; gap: 1rem; }\n"
        "        #log-container { background-color: #f8f9fa; border: 1px solid var(--cor-borda); border-radius: 4px; padding: 1rem; height: 150px; overflow-y: auto; font-family: 'Courier New', monospace; font-size: 0.9rem; }\n"
        "        #log-container p { padding-bottom: 0.5rem; border-bottom: 1px solid #eee; }\n"
        "        #log-container p:last-child { border-bottom: none; }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"

        "<header class=\"main-header\">\n"
        "    <h1>Painel de Controle - Armazém Automatizado XYZ</h1>\n"
        "</header>\n"

        "<main class=\"dashboard-container\">\n"

        "    <div class=\"warehouse-view-column\">\n"
        "        <section id=\"visualizacao-rack\">\n"
        "            <h2>Layout do Armazém</h2>\n"
        "            <div class=\"warehouse-layout\">\n"
        "                <div id=\"entry-conveyor\" class=\"conveyor\">\n"
        "                    <h3>Entrada</h3>\n"
        "                    <div class=\"pallet-info\" id=\"pallet-on-entry\"><p>ID: ABC-123</p></div>\n"
        "                </div>\n"
        "                <div class=\"rack-container\">\n"
        "                    <div class=\"rack-cell occupied\" data-position=\"D1\">D1</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"D2\">D2</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"D3\">D3</div>\n"
        "                    <div class=\"rack-cell occupied\" data-position=\"D4\">D4</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"D5\">D5</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"C1\">C1</div>\n"
        "                    <div class=\"rack-cell occupied\" data-position=\"C2\">C2</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"C3\">C3</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"C4\">C4</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"C5\">C5</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"B1\">B1</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"B2\">B2</div>\n"
        "                    <div class=\"rack-cell occupied\" data-position=\"B3\">B3</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"B4\">B4</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"B5\">B5</div>\n"
        "                    <div class=\"rack-cell occupied\" data-position=\"A1\">A1</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"A2\">A2</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"A3\">A3</div>\n"
        "                    <div class=\"rack-cell occupied\" data-position=\"A4\">A4</div>\n"
        "                    <div class=\"rack-cell\" data-position=\"A5\">A5</div>\n"
        "                </div>\n"
        "                <div id=\"exit-conveyor\" class=\"conveyor\">\n"
        "                    <h3>Saída</h3>\n"
        "                    <div class=\"pallet-info\" id=\"pallet-on-exit\"></div>\n"
        "                </div>\n"
        "            </div>\n"
        "        </section>\n"
        "    </div>\n"

        "    <div class=\"controls-column\">\n"
        "        <section id=\"painel-controle\">\n"
        "            <h2>Painel de Controle</h2>\n"
        "            <div class=\"control-group\" id=\"pallet-operations\">\n"
        "                <h3>Operações com Pallets</h3>\n"
        "                <button onclick=\"enviarAcao('store_pallet')\">Iniciar Armazenamento</button>\n"
        "                <label for='pallet-position-input'>Retirar pallet da posição:</label>\n"
        "                <input type='text' id='pallet-position-input' placeholder='Ex: B3'>\n"
        "                <button onclick=\"enviarAcao('retrieve_pallet')\">Iniciar Retirada</button>\n"
        "            </div>\n"
        "            <div class=\"control-group\" id=\"manual-control\">\n"
        "                <h3>Controle Manual</h3>\n"
        "                <label for='coord-x'>Eixo X:</label>\n"
        "                <input type='number' id='coord-x' value='0'>\n"
        "                <label for='coord-y'>Eixo Y:</label>\n"
        "                <input type='number' id='coord-y' value='0'>\n"
        "                <label for='coord-z'>Eixo Z:</label>\n"
        "                <input type='number' id='coord-z' value='0'>\n"
        "                <button onclick=\"enviarAcao('move_coords')\">Mover para Coordenada</button>\n"
        "                <div id='electromagnet-control'>\n"
        "                    <button onclick=\"enviarAcao('toggle_magnet')\">Ativar Eletroímã</button>\n"
        "                    <span>Status: <b id='electromagnet-status'>Desativado</b></span>\n"
        "                </div>\n"
        "            </div>\n"
        "        </section>\n"
        "        <section id=\"historico\">\n"
        "            <h2>Histórico de Movimentações</h2>\n"
        "            <div id=\"log-container\">Carregando histórico...</div>\n"
        "        </section>\n"
        "    </div>\n"

        "</main>\n"

        "<footer class=\"main-footer\">\n"
        "    <p>Interface de Controle v1.0 - Status do Sistema: <span id=\"system-status\">Online</span></p>\n"
        "</footer>\n"

        "<script>\n"
        "async function fetchHistorico() {\n"
        "    const container = document.getElementById('log-container');\n"
        "    container.innerHTML = 'Carregando histórico...';\n"
        "    try {\n"
        "        const response = await fetch('http://192.168.1.9:5000/historico');\n"
        "        if (!response.ok) throw new Error('Erro ao buscar histórico');\n"
        "        const data = await response.json();\n"
        "        if (data.length === 0) { container.innerHTML = 'Nenhum histórico encontrado.'; return; }\n"
        "        let htmlContent = '';\n"
        "        data.forEach(item => {\n"
        "            const [id, acao, dataHora] = item;\n"
        "            htmlContent += `<p>${dataHora} - ${acao}</p>`;\n"
        "        });\n"
        "        container.innerHTML = htmlContent;\n"
        "    } catch (err) {\n"
        "        console.error(err);\n"
        "        container.innerHTML = 'Erro ao carregar histórico.';\n"
        "    }\n"
        "}\n"
        "async function enviarAcao(acao) {\n"
        "    await fetch(`./${acao}`);\n"
        "    fetchHistorico();\n"
        "}\n"
        "window.onload = fetchHistorico;\n"
        "</script>\n"

        "</body>\n"
        "</html>\n"
    );
}
