#include <stdio.h>
#include <string.h>
#include <stdlib.h>

// Cria a resposta HTML em um buffer maior
char html[8192];

extern char html[8192];

// Preenche o array html com o conteúdo do painel de controle do armazém
void preencher_html() {
    snprintf(html, sizeof(html),
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html\r\n"
        "\r\n"
        "<!DOCTYPE html>\n"
        "<html lang=\"pt-BR\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Painel de Controle - Armazém XYZ</title>\n"
        "    <style>\n"
        "        :root {\n"
        "            --cor-primaria: #005A9C;\n"
        "            --cor-fundo: #f4f7f9;\n"
        "            --cor-painel: #ffffff;\n"
        "            --cor-texto: #333333;\n"
        "            --cor-sucesso: #28a745;\n"
        "            --cor-aviso: #ffc107;\n"
        "            --cor-borda: #dee2e6;\n"
        "            --sombra-suave: 0 4px 8px rgba(0,0,0,0.05);\n"
        "        }\n"
        "\n"
        "        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
        "        body {\n"
        "            font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif;\n"
        "            background-color: var(--cor-fundo);\n"
        "            color: var(--cor-texto);\n"
        "            line-height: 1.6;\n"
        "        }\n"
        "\n"
        "        .main-header, .main-footer {\n"
        "            background-color: var(--cor-primaria);\n"
        "            color: white;\n"
        "            padding: 1rem 2rem;\n"
        "            text-align: center;\n"
        "        }\n"
        "\n"
        "        .dashboard-container {\n"
        "            display: flex;\n"
        "            flex-wrap: wrap;\n"
        "            padding: 1.5rem;\n"
        "            gap: 1.5rem;\n"
        "        }\n"
        "\n"
        "        .warehouse-view-column { flex: 2; min-width: 350px; }\n"
        "        .controls-column { flex: 1; min-width: 300px; }\n"
        "\n"
        "        section {\n"
        "            background-color: var(--cor-painel);\n"
        "            padding: 1.5rem;\n"
        "            border-radius: 8px;\n"
        "            box-shadow: var(--sombra-suave);\n"
        "            margin-bottom: 1.5rem;\n"
        "        }\n"
        "\n"
        "        h2, h3 { margin-bottom: 1rem; color: var(--cor-primaria); }\n"
        "        h3 { font-size: 1.1rem; border-bottom: 1px solid var(--cor-borda); padding-bottom: 0.5rem; }\n"
        "\n"
        "        .warehouse-layout {\n"
        "            display: flex; align-items: center; justify-content: center; gap: 1rem;\n"
        "            flex-wrap: wrap;\n"
        "        }\n"
        "\n"
        "        .rack-container {\n"
        "            display: grid;\n"
        "            grid-template-columns: repeat(5, 1fr);\n"
        "            gap: 0.5rem;\n"
        "            flex-grow: 1;\n"
        "        }\n"
        "\n"
        "        .rack-cell {\n"
        "            background-color: #e9ecef;\n"
        "            border: 1px solid #ccc;\n"
        "            border-radius: 4px;\n"
        "            aspect-ratio: 1 / 1;\n"
        "            display: flex; align-items: center; justify-content: center;\n"
        "            font-weight: bold; font-size: 0.9rem;\n"
        "            transition: background-color 0.3s ease;\n"
        "            cursor: pointer;\n"
        "        }\n"
        "\n"
        "        .rack-cell.occupied { background-color: var(--cor-aviso); color: var(--cor-texto); border-color: #e6a800; }\n"
        "        .rack-cell.occupied:hover { background-color: #e6a800; transform: scale(1.05); }\n"
        "        .rack-cell:not(.occupied) { cursor: not-allowed; opacity: 0.6; }\n"
        "\n"
        "        .legend { display: flex; justify-content: center; gap: 2rem; margin-top: 1rem; padding: 1rem; background-color: #f8f9fa; border-radius: 4px; flex-wrap: wrap; }\n"
        "        .legend-item { display: flex; align-items: center; gap: 0.5rem; }\n"
        "        .legend-color { width: 20px; height: 20px; border-radius: 4px; border: 1px solid #ccc; }\n"
        "        .legend-color.occupied { background-color: var(--cor-aviso); }\n"
        "        .legend-color.empty { background-color: #e9ecef; }\n"
        "\n"
        "        .conveyor { border: 2px dashed var(--cor-primaria); padding: 1rem 0.5rem; min-height: 200px; display: flex; flex-direction: column; align-items: center; text-align: center; }\n"
        "        .pallet-info { margin-top: 1rem; font-weight: bold; color: var(--cor-sucesso); }\n"
        "\n"
        "        form { display: flex; flex-direction: column; gap: 0.75rem; }\n"
        "        input[type=\"text\"], input[type=\"number\"], input[type=\"date\"] { width: 100%; padding: 0.75rem; border: 1px solid var(--cor-borda); border-radius: 4px; font-size: 1rem; }\n"
        "        button { padding: 0.75rem 1rem; border: none; border-radius: 4px; background-color: var(--cor-primaria); color: white; font-size: 1rem; font-weight: bold; cursor: pointer; transition: background-color 0.2s ease; }\n"
        "        button:hover { background-color: #004a80; }\n"
        "\n"
        "        /* ======== Responsividade ======== */\n"
        "        @media (max-width: 1024px) {\n"
        "            .dashboard-container { flex-direction: column; }\n"
        "            .warehouse-layout { flex-direction: column; }\n"
        "        }\n"
        "\n"
        "        @media (max-width: 768px) {\n"
        "            .dashboard-container {\n"
        "                flex-direction: column;\n"
        "             }\n"
        "            .rack-container { grid-template-columns: repeat(3, 1fr); }\n"
        "            .legend { gap: 1rem; }\n"
        "        }\n"
        "\n"
        "        @media (max-width: 480px) {\n"
        "            .warehouse-view-column,\n"
        "            .controls-column {\n"
        "               min-width: 100%;\n"
        "            }\n"
        "            h1 { font-size: 1.2rem; }\n"
        "            h2 { font-size: 1rem; }\n"
        "            h3 { font-size: 0.9rem; }\n"
        "            .rack-container { grid-template-columns: repeat(2, 1fr); }\n"
        "            button { font-size: 0.9rem; padding: 0.5rem; }\n"
        "        }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "    <header class=\"main-header\">\n"
        "        <h1>Painel de Controle - Armazém Automatizado XYZ</h1>\n"
        "    </header>\n"
        "    <main class=\"dashboard-container\">\n"
        "\n"
        "        <div class=\"warehouse-view-column\">\n"
        "            <section id=\"visualizacao-rack\">\n"
        "                <h2>Layout do Armazém</h2>\n"
        "                <div class=\"warehouse-layout\">\n"
        "                    \n"
        "                    <div id=\"entry-conveyor\" class=\"conveyor\">\n"
        "                        <h3>Entrada</h3>\n"
        "                        <div class=\"pallet-info\" id=\"pallet-on-entry\">\n"
        "                            <p>ID: ABC-123</p> \n"
        "                        </div>\n"
        "                    </div>\n"
        "\n"
        "                    <div class=\"rack-container\">\n"
        "                        <div class=\"rack-cell occupied\" data-position=\"A1\">A1</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"A2\">A2</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"A3\">A3</div>\n"
        "                        <div class=\"rack-cell occupied\" data-position=\"A4\">A4</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"A5\">A5</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"B1\">B1</div>\n"
        "                        <div class=\"rack-cell occupied\" data-position=\"B2\">B2</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"B3\">B3</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"B4\">B4</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"B5\">B5</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"C1\">C1</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"C2\">C2</div>\n"
        "                        <div class=\"rack-cell occupied\" data-position=\"C3\">C3</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"C4\">C4</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"C5\">C5</div>\n"
        "                        <div class=\"rack-cell occupied\" data-position=\"D1\">D1</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"D2\">D2</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"D3\">D3</div>\n"
        "                        <div class=\"rack-cell occupied\" data-position=\"D4\">D4</div>\n"
        "                        <div class=\"rack-cell\" data-position=\"D5\">D5</div>\n"
        "                    </div>\n"
        "                    \n"
        "                    <div id=\"exit-conveyor\" class=\"conveyor\">\n"
        "                        <h3>Saída</h3>\n"
        "                         <div class=\"pallet-info\" id=\"pallet-on-exit\">\n"
        "                            </div>\n"
        "                    </div>\n"
        "\n"
        "                </div>\n"
        "                \n"
        "                <div class=\"legend\">\n"
        "                    <div class=\"legend-item\">\n"
        "                        <div class=\"legend-color occupied\"></div>\n"
        "                        <span>Ocupado (com pallet armazenado)</span>\n"
        "                    </div>\n"
        "                    <div class=\"legend-item\">\n"
        "                        <div class=\"legend-color empty\"></div>\n"
        "                        <span>Vazio (sem pallet)</span>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </section>\n"
        "        </div>\n"
        "\n"
        "        <div class=\"controls-column\">\n"
        "            <section id=\"painel-controle\">\n"
        "                <h2>Painel de Controle</h2>\n"
        "\n"
        "                <div class=\"control-group\" id=\"pallet-operations\">\n"
        "                    <h3>Operações com Pallets</h3>\n"
        "                    <form id=\"store-form\">\n"
        "                        <p>Armazenar pallet da esteira de entrada.</p>\n"
        "                        <button type=\"submit\">Iniciar Armazenamento</button>\n"
        "                    </form>\n"
        "                    <form id=\"retrieve-form\">\n"
        "                        <label for=\"pallet-position-input\">Retirar pallet da posição:</label>\n"
        "                        <input type=\"text\" id=\"pallet-position-input\" name=\"position\" placeholder=\"Ex: B3\" required>\n"
        "                        <button type=\"submit\">Iniciar Retirada</button>\n"
        "                    </form>\n"
        "                </div>\n"
        "\n"
        "                <div class=\"control-group\" id=\"manual-control\">\n"
        "                    <h3>Controle Manual</h3>\n"
        "                    <form id=\"move-form\">\n"
        "                        <label for=\"coord-x\">Eixo X:</label>\n"
        "                        <input type=\"number\" id=\"coord-x\" name=\"x\" min=\"0\" value=\"0\">\n"
        "                        <label for=\"coord-y\">Eixo Y:</label>\n"
        "                        <input type=\"number\" id=\"coord-y\" name=\"y\" min=\"0\" value=\"0\">\n"
        "                        <label for=\"coord-z\">Eixo Z:</label>\n"
        "                        <input type=\"number\" id=\"coord-z\" name=\"z\" min=\"0\" value=\"0\">\n"
        "                        <button type=\"submit\">Mover para Coordenada</button>\n"
        "                    </form>\n"
        "                    <div id=\"electromagnet-control\">\n"
        "                         <button id=\"electromagnet-toggle-btn\">Ativar Eletroímã</button>\n"
        "                         <span>Status: <b id=\"electromagnet-status\">Desativado</b></span>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </section>\n"
        "            \n"
        "            <section id=\"historico\">\n"
        "                <h2>Histórico de Movimentações</h2>\n"
        "                <form id=\"history-filter-form\">\n"
        "                    <label for=\"filter-date\">Filtrar por data:</label>\n"
        "                    <input type=\"date\" id=\"filter-date\" name=\"date\">\n"
        "                    <button type=\"submit\">Filtrar</button>\n"
        "                </form>\n"
        "                <div id=\"log-container\">\n"
        "                    <p>15:00:12 - Pallet XYZ-789 retirado da posição A2.</p>\n"
        "                    <p>14:58:34 - Mecanismo movido para X:150 Y:300 Z:50.</p>\n"
        "                    <p>14:55:01 - Pallet ABC-123 armazenado na posição A5.</p>\n"
        "                </div>\n"
        "            </section>\n"
        "        </div>\n"
        "\n"
        "    </main>\n"
        "\n"
        "    <div class=\"popup-overlay\" id=\"popup-overlay\">\n"
        "        <div class=\"popup\">\n"
        "            <h3>Confirmar Remoção</h3>\n"
        "            <p>Deseja remover o pallet da posição <span id=\"popup-position\"></span>?</p>\n"
        "            <div class=\"popup-buttons\">\n"
        "                <button id=\"confirm-remove\">Sim</button>\n"
        "                <button class=\"cancel\" id=\"cancel-remove\">Não</button>\n"
        "            </div>\n"
        "        </div>\n"
        "    </div>\n"
        "\n"
        "    <footer class=\"main-footer\">\n"
        "        <p>Interface de Controle v1.0 - Status do Sistema: <span id=\"system-status\">Online</span></p>\n"
        "    </footer>\n"
        "\n"
        "    <script>\n"
        "        document.addEventListener('DOMContentLoaded', function() {\n"
        "            const rackCells = document.querySelectorAll('.rack-cell');\n"
        "            const popupOverlay = document.getElementById('popup-overlay');\n"
        "            const popupPosition = document.getElementById('popup-position');\n"
        "            const confirmButton = document.getElementById('confirm-remove');\n"
        "            const cancelButton = document.getElementById('cancel-remove');\n"
        "            let currentSlot = null;\n"
        "\n"
        "            rackCells.forEach(cell => {\n"
        "                cell.addEventListener('click', function() {\n"
        "                    if (this.classList.contains('occupied')) {\n"
        "                        currentSlot = this.getAttribute('data-position');\n"
        "                        popupPosition.textContent = currentSlot;\n"
        "                        popupOverlay.style.display = 'flex';\n"
        "                    }\n"
        "                });\n"
        "            });\n"
        "\n"
        "            confirmButton.addEventListener('click', function() {\n"
        "                if (currentSlot) {\n"
        "                    const url = new URL(window.location);\n"
        "                    url.searchParams.set('slot', currentSlot);\n"
        "                    window.location.href = url.toString();\n"
        "                }\n"
        "                popupOverlay.style.display = 'none';\n"
        "            });\n"
        "\n"
        "            cancelButton.addEventListener('click', function() {\n"
        "                popupOverlay.style.display = 'none';\n"
        "                currentSlot = null;\n"
        "            });\n"
        "\n"
        "            popupOverlay.addEventListener('click', function(e) {\n"
        "                if (e.target === popupOverlay) {\n"
        "                    popupOverlay.style.display = 'none';\n"
        "                    currentSlot = null;\n"
        "                }\n"
        "            });\n"
        "        });\n"
        "    </script>\n"
        "\n"
        "</body>\n"
        "</html>\n"
    );
}
